package MainPackage;


import RMI.Viewer;
import java.awt.BorderLayout;


/**
 *
 * @author  benbac
 */
public class Player extends javax.swing.JFrame {
    
    public ScreenPlayer screenPlayer;
    public Recorder recorder;
    public Viewer viewer;
    
    /** Creates new form MainFrame */
    public Player(String args[]) {
        initComponents();
        initScreenPlayer();
        
        recorder = new Recorder(this, args);
        recorder.start();
        
        //Dimension dimScreenSize = Toolkit.getDefaultToolkit().getScreenSize();      
    }
    
    public void initScreenPlayer() {
        screenPlayer = new ScreenPlayer(this);
        
        jPanel1.setLayout(new BorderLayout()); 
        jPanel1.add(screenPlayer);
       
       /* javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel1);
        
        jPanel1.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(screenPlayer, 
                    Short.MAX_VALUE, Short.MAX_VALUE, Short.MAX_VALUE)
                .addContainerGap(0, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(screenPlayer, 
                    Short.MAX_VALUE, Short.MAX_VALUE, Short.MAX_VALUE)
                .addContainerGap(0, Short.MAX_VALUE))
        );   */
    }   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBtnStartStop = new javax.swing.JButton();
        jBtnPauseContinue = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jBtnViewCtrl = new javax.swing.JButton();
        jBtnFullNormal = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jBtnPartialComplete = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSlider1 = new javax.swing.JSlider();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jBtnAbout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Remote Desktop [jrdesktop] 0.1 Beta 2");

        jToolBar1.setRollover(true);

        jBtnStartStop.setText("Start");
        jBtnStartStop.setFocusable(false);
        jBtnStartStop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnStartStop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnStartStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStartStopActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnStartStop);

        jBtnPauseContinue.setText("Pause");
        jBtnPauseContinue.setFocusable(false);
        jBtnPauseContinue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnPauseContinue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnPauseContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPauseContinueActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnPauseContinue);
        jToolBar1.add(jSeparator2);

        jBtnViewCtrl.setText("View only");
        jBtnViewCtrl.setFocusable(false);
        jBtnViewCtrl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnViewCtrl.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnViewCtrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnViewCtrlActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnViewCtrl);

        jBtnFullNormal.setText("Full screen");
        jBtnFullNormal.setFocusable(false);
        jBtnFullNormal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnFullNormal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnFullNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFullNormalActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnFullNormal);
        jToolBar1.add(jSeparator1);

        jBtnPartialComplete.setText("Custom screen");
        jBtnPartialComplete.setFocusable(false);
        jBtnPartialComplete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnPartialComplete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnPartialComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPartialCompleteActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnPartialComplete);
        jToolBar1.add(jSeparator3);

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Compression quality");
        jCheckBox1.setFocusable(false);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jCheckBox1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jCheckBox1);

        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(10);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintTicks(true);
        jSlider1.setFocusable(false);
        jSlider1.setMaximumSize(new java.awt.Dimension(150, 33));
        jSlider1.setPreferredSize(new java.awt.Dimension(150, 33));
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jToolBar1.add(jSlider1);
        jToolBar1.add(jSeparator4);

        jBtnAbout.setText("About");
        jBtnAbout.setFocusable(false);
        jBtnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAboutActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnAbout);

        jPanel1.setBackground(java.awt.Color.black);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-700)/2, (screenSize.height-450)/2, 700, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnStartStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStartStopActionPerformed
        if (recorder.isRecording()) {
            recorder.Stop();
            jBtnStartStop.setText("Start");
            jBtnPauseContinue.setText("Pause");
            jBtnViewCtrl.setText("View only");
            jBtnFullNormal.setText("Full screen");
            jBtnPartialComplete.setText("Custom screen");
        } else {
            recorder.Start();
            jBtnStartStop.setText("Stop");
        }
    }//GEN-LAST:event_jBtnStartStopActionPerformed

    private void jBtnPauseContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPauseContinueActionPerformed
        if (recorder.isRecording()) {
            recorder.setPause(!recorder.isPaused());
            if (recorder.isPaused())
                jBtnPauseContinue.setText("Continue");
            else
                jBtnPauseContinue.setText("Pause");
        }
    }//GEN-LAST:event_jBtnPauseContinueActionPerformed

    private void jBtnViewCtrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnViewCtrlActionPerformed
        if (recorder.isRecording()) {
            recorder.setViewOnly(!recorder.isViewOnly());
            if (recorder.isViewOnly())
                jBtnViewCtrl.setText("Full control");
            else
                jBtnViewCtrl.setText("View only");
        }
    }//GEN-LAST:event_jBtnViewCtrlActionPerformed

    private void jBtnFullNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFullNormalActionPerformed
        if (recorder.isRecording()) {
            screenPlayer.setScreenMode(!screenPlayer.isFullScreenMode());
            if (screenPlayer.isFullScreenMode())
                jBtnFullNormal.setText("Normal screen");
            else
                jBtnFullNormal.setText("Full screen");
        }
    }//GEN-LAST:event_jBtnFullNormalActionPerformed

    private void jBtnPartialCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPartialCompleteActionPerformed
        if (recorder.isRecording()) {
            if (screenPlayer.isPartialScreenSizeMode()) {
                jBtnPartialComplete.setText("Custom screen");
                screenPlayer.setDefaultScreenRect();
            } else
                screenPlayer.startSelection();
        }
    }//GEN-LAST:event_jBtnPartialCompleteActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        if (jSlider1.getValueIsAdjusting()) {
            screenPlayer.setCompressionQuality((float)jSlider1.getValue() / 10.0f); 
        }
    }//GEN-LAST:event_jSlider1StateChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        jSlider1.setEnabled(jCheckBox1.isSelected());
        if (!jCheckBox1.isSelected())
            screenPlayer.setCompressionQuality(-1);
        else
           jSlider1StateChanged(null);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jBtnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAboutActionPerformed
        AboutJFrame.main(null);
}//GEN-LAST:event_jBtnAboutActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Player(args).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAbout;
    private javax.swing.JButton jBtnFullNormal;
    public javax.swing.JButton jBtnPartialComplete;
    private javax.swing.JButton jBtnPauseContinue;
    private javax.swing.JButton jBtnStartStop;
    private javax.swing.JButton jBtnViewCtrl;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    
}
